// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxBCOnVEZirGMmcu1YJalg-aw3E0Hed7k',
    appId: '1:687583059034:web:5eeba5db68d1ae6d9d4c63',
    messagingSenderId: '687583059034',
    projectId: 'wordle-solver-kyle',
    authDomain: 'wordle-solver-kyle.firebaseapp.com',
    storageBucket: 'wordle-solver-kyle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByUF0ty89vznI68IvUPIbQ41psLqTCV6M',
    appId: '1:687583059034:android:e4943bd0671d55169d4c63',
    messagingSenderId: '687583059034',
    projectId: 'wordle-solver-kyle',
    storageBucket: 'wordle-solver-kyle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElqxiw4zRGiR5Xx7I4j0hfeDt-3dwlFI',
    appId: '1:687583059034:ios:dde2d1048cf9c52d9d4c63',
    messagingSenderId: '687583059034',
    projectId: 'wordle-solver-kyle',
    storageBucket: 'wordle-solver-kyle.firebasestorage.app',
    iosBundleId: 'com.example.wordleSolver',
  );
}
