name: Update Dictionaries

on:
  push:
    branches: [ main ]
    paths: [ 'assets/words/**' ]
  workflow_dispatch:

jobs:
  update-dictionaries:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate dictionary files
      run: |
        echo "Validating dictionary files..."
        for file in assets/words/*.json; do
          if [ -f "$file" ]; then
            echo "Validating $file"
            python3 -m json.tool "$file" > /dev/null
            echo "✅ $file is valid JSON"
          fi
        done
        
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: wordle-solver-kyle
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WORDLE_SOLVER_KYLE }}
        
    - name: Upload dictionaries using bash script
      run: ./scripts/upload-dictionaries.sh
